### ISSUE TITLE
Parallel read from Elasticsearch via dask

### ISSUE THREAD

**Issue by avlahop** [ContinuumIO/intake-elasticsearch#6]
After a discussion with @martindurant it was proposed to me to implement an implementation of parallel reading from Elasticsearch with dask. There exist a dask implementation in the plugin [here](https://github.com/ContinuumIO/intake-elasticsearch/blob/master/intake_elasticsearch/elasticsearch_table.py#L63) but it fetches the data within one partition. There are two ways to deal with fetchin data in parallel and both ways use the scroll and slice functionality of elasticsearch as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html). Using the slice plugin we could slice the data in to the number of wanted partitions like this:

```
GET /twitter/_search?scroll=1m
{
    "slice": {
        "id": 0, 
        "max": #wanted number of partitions 
    },
    "query": {
        "match" : {
            "title" : "elasticsearch"
        }
    }
}
```

the code could be modified something like this:

``` python
def to_dask(self, no_of_partitions):
     """Make single-partition lazy dask data-frame"""
    import dask.dataframe as dd
    from dask import delayed
    self.discover()
    partis = []
    for partition in no_of_partitions:
        part = delayed(self._get_partition(partition, no_of_partitions))
        parts.append(part)
    return dd.from_delayed(parts, meta=self.dtype)
```
and `_get_partition` should be responsible for creating the respected query according to the partition number and the no_of_partitions

This is easy and fast implementation. On the down side of things, every request to the ES cluster will go through the master node, master node will transfer the query to all data nodes, the send data back to master node and then data are sent back via the master node. 
On the other hand, if  you would like to take advantage of greater network throuput we could write functionality that would do the following tasks:
- Discover Nodes and their publish adresses. In ES each data node implements a REST API service and they can be accessed independently
- Discover information on the index requested: 
  - Shards info (number, location)
  - meta info (this is already implemented as I have undrstood
It could then use the preference functionality of Elasticsearch describes [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html) to send the request to the node that holds the data of each shard. It could also use number of partitions to divide each shard either by defining the number or defining the number of documents per partition/task. 

The latter functionality is used by [ES Hadoop connector](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/performance.html) and is implemented in my project [dask-elk](https://github.com/avlahop/dask-elk)

What do you think ? Which would you like?

**Comment by martindurant** [comment]
The two need not be mutually exclusive, we could have both the simple and the more complicated method implemented, and available to catalog authors. Both are improvements on the single-partition approach, and I'd be glad to see them.
What is the downside to the fully distributed method in dask-elk? Do you mean that you would till have to expend considerable effort to implement it? 

I should note that the dask workers are not necessarily on the same machine(s) as the ES servers, so there will be a limited number of systems where it applies. Also note that the splitting of the data into partitions applies both to data-frame-like results sets and more general nested data for Bags.

**Comment by martindurant** [comment]
Does the fully distributed method offer a convenient way to be tested?

**Comment by avlahop** [comment]
> What is the downside to the fully distributed method in dask-elk? Do you mean that you would till have to expend considerable effort to implement it?

Yes it needs more logic and changes to be made so the whole state can be represented. If I were to use my library as a dependency, maybe it would be faster. Not as much effort since I have already implemented some of it, but need to copy and adapt the functionality with yours.

> I should note that the dask workers are not necessarily on the same machine(s) as the ES servers, so there will be a limited number of systems where it applies.

I think that it is not supposed to. Running dask workers on the same machine(s) as the ES data nodes, would of course means faster  Network I/O. But then you can not scale ES and Dask workers independantly.  If you have it in separate macines, being able to request data from each data node individually would mean more throughput than asking it from the master. E.g:

If you have  3 workers with 10Gbit  eth cards and your ES cluster also and requesting from one master then the throuput is defined by the slowest side, which is the master. You can handle theoretically 3x10Gbit but getting only 1. Instead if you connect to each node/shard seperatelly then you are utilizing your throuput better. 

> Also note that the splitting of the data into partitions applies both to data-frame-like results sets and more general nested data for Bags.

You already tranform them in to dataframe when fetching the data. You want other functions implemented for bags?

> Does the fully distributed method offer a convenient way to be tested?
What do you mean by that? Unit? Functional? Manually?
