### ISSUE TITLE
intake.registry only shows ElasticSearchTableSource

### ISSUE THREAD

**Issue by paularmand** [ContinuumIO/intake-elasticsearch#9]
Intake registry gives me the wrong result for elasticsearch_seq and no elasticsearch_table

Result:
> intake.registry  # results in the following dict
{'yaml_file_cat': intake.catalog.local.YAMLFileCatalog,
 'yaml_files_cat': intake.catalog.local.YAMLFilesCatalog,
 'avro_sequence': intake_avro.source.AvroSequenceSource,
 'avro_table': intake_avro.source.AvroTableSource,
 'elasticsearch_seq': intake_elasticsearch.elasticsearch_table.ElasticSearchTableSource,
 'sql_cat': intake_sql.sql_cat.SQLCatalog,
 'sql': intake_sql.intake_sql.SQLSource,
 'sql_auto': intake_sql.intake_sql.SQLSourceAutoPartition,
 'sql_manual': intake_sql.intake_sql.SQLSourceManualPartition,
 'csv': intake.source.csv.CSVSource,
 'textfiles': intake.source.textfiles.TextFilesSource,
 'catalog': intake.catalog.base.Catalog,
 'intake_remote': intake.catalog.base.RemoteCatalog,
 'numpy': intake.source.npy.NPySource}

Expected result:
I expected two entries:
 'elasticsearch_table': intake_elasticsearch.elasticsearch_table.ElasticSearchTableSource,
 'elasticsearch_seq': intake_elasticsearch.elasticsearch_seq.ElasticSearchSeqSource,

Question:
Is this expected behaviour, or should the seqSource also be reachable for the user of the plugin?

env:
+ jupyterhub
+ I installed it via conda and via pip (latest version of intake and intake-elasticsearch)

**Comment by martindurant** [comment]
The two drivers should indeed be in the registry. Does `import intake_elasticsearch` give any error?

On January 29, 2019 1:09:28 PM EST, Paul-Armand Verhaegen <notifications@github.com> wrote:
>Intake registry gives me the wrong result for elasticsearch_seq and no
>elasticsearch_table
>
>Result:
>> intake.registry  # results in the following dict
>{'yaml_file_cat': intake.catalog.local.YAMLFileCatalog,
> 'yaml_files_cat': intake.catalog.local.YAMLFilesCatalog,
> 'avro_sequence': intake_avro.source.AvroSequenceSource,
> 'avro_table': intake_avro.source.AvroTableSource,
>'elasticsearch_seq':
>intake_elasticsearch.elasticsearch_table.ElasticSearchTableSource,
> 'sql_cat': intake_sql.sql_cat.SQLCatalog,
> 'sql': intake_sql.intake_sql.SQLSource,
> 'sql_auto': intake_sql.intake_sql.SQLSourceAutoPartition,
> 'sql_manual': intake_sql.intake_sql.SQLSourceManualPartition,
> 'csv': intake.source.csv.CSVSource,
> 'textfiles': intake.source.textfiles.TextFilesSource,
> 'catalog': intake.catalog.base.Catalog,
> 'intake_remote': intake.catalog.base.RemoteCatalog,
> 'numpy': intake.source.npy.NPySource}
>
>
>Expected result:
>I expected two entries:
>'elasticsearch_table':
>intake_elasticsearch.elasticsearch_table.ElasticSearchTableSource,
>'elasticsearch_seq':
>intake_elasticsearch.elasticsearch_seq.ElasticSearchSeqSource,
>
>Question:
>Is this expected behaviour, or should the seqSource also be reachable
>for the user of the plugin?
>
>env:
>+ jupyterhub
>+ I installed it via conda and via pip (latest version of intake and
>intake-elasticsearch)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ContinuumIO/intake-elasticsearch/issues/9

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martindurant** [comment]
At a quick test, I see that the import still works, and intake does still pick up elasticsearch upon import and apply to the registry. One fault was, the two drivers accidentally had the same name - I will push a fix for that now, and maybe go through the process of migrating the distribution to conda-forge (it will continue to be available on the intake channel too).

**Comment by martindurant** [comment]
(note that you can always refer to the driver directly, e.g., `'intake_elasticsearch.elasticsearch_seq.ElasticSearchSeqSource'`)

**Comment by paularmand** [comment]
Thanks @martindurant. 
Both plugin classes are visible in the intake.registry now. This issue can be closed.

**Comment by martindurant** [comment]
Excellent. I would be interested to know your use of Intake, if you care to contribute your story. A new issue in this repo would be ideal.
